### PR TITLE
Added translation (admin_lang.php from 225 to 369)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by enlivenapp** [comment]
ugh...  conflicts.  

It appears changes to auth_lang was meant to be to admin_lang?

**Comment by keeganpa** [comment]
My PR include the full translated version of auth_lang.php, if he wants to change it again, it might be because he wanted to do to much when unifying our work i guess

**Comment by Ignamarte** [comment]
yup that's the wrong file name, the file named auth_lang.php should be named admin_lang.php

**Comment by enlivenapp** [comment]
Do you want me to do it or do you want to update your PR?

**Pull request closed without merging**
