### PR TITLE
update grammar

### PR DESCRIPTION
**Pull request by totoprayogo1916**

### CODE REVIEW

**Comment by enlivenapp** [comment]
Sadly, I don't know the language.  There's no conflicts, so I approved it.

@suhindra

**Review by enlivenapp — DISMISSED** [review]

**Comment by suhindra** [comment]
@enlivenapp this is not a grammar improvement. Most Indonesian natives forget about this and mistakes are common.

@mylastof Be careful to differentiate between "di" as prefix (awalan) and "di" as showing the place (kata depan).  If the word "di" is followed by a verb, it is a prefix. [https://id.wikipedia.org/wiki/Preposisi](url)

**Comment by enlivenapp** [comment]
@suhindra, just covering my bases.  This PR should be rejected?

**Comment by suhindra** [comment]
Yes, this PR should be rejected.

**Pull request closed without merging**
